# Generated by Django 4.1.5 on 2023-03-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ministries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ministries",
            name="emel",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
