# Generated by Django 4.1.5 on 2023-04-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_report_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
